Remove Embedded Native Dlls from managed Scintilla dll
VPKSoft/Scintilla.NET pull request #43
Opened 2023-01-18 20:53 UTC by RobSwDev

Remove Embedded Native Dlls from managed Scintilla dll
They are copied as part of the build or nuget restore process now

I branched the original repo at 73fd0cfdebc8518cd0fff33e59138ac453d41bef (tag: v.5.3.2.1) 
(there are conflicts against master due to the changes since the introduction of the new abstractions assembly)

2023-01-19 05:04 UTC, VPKSoft approved these changes

2023-01-19 05:04 UTC, VPKSoft commented on native/x64/version.txt
> +Lexilla: 5.1.4
This also has different version:
![image](https://user-images.githubusercontent.com/40712699/213359538-856ec7ad-7385-4004-b23e-833c9bb4bda7.png)

2023-01-19 05:04 UTC, VPKSoft commented on native/x86/version.txt
> +Scintilla: 5.1.5
The version conflicts with the DLL files as above.

2023-01-19 05:04 UTC, VPKSoft commented on native/x86/version.txt
> +Lexilla: 5.1.4
The version conflicts with the DLL files as above.

2023-01-19 05:17 UTC, VPKSoft requested changes
Something seems to be wrong with the DLL versions. Otherwise looks good.

2023-01-19 09:06 UTC, RobSwDev commented on native/x64/version.txt
> +Scintilla: 5.1.5
These are simply the existing files, copied from elsewhere in the repository.
I.e. from `Shared\x64\Scintilla.zip` and `Shared\x64\version.txt`
I didn't change anything. Were the versions in the text file already out of sync with the dll properties?

2023-01-19 14:42 UTC, VPKSoft approved these changes

2023-01-19 14:43 UTC, merged

2023-01-20 02:43 UTC, VPKSoft commented
Hi,
I should have tested this better, the WinForms designer seems to have stopped working with the 5.3.2.2 version. I'm going to have to roll back.

2023-01-20 02:47 UTC, VPKSoft commented
See:
![image](https://user-images.githubusercontent.com/40712699/213607250-be06d2ea-1393-4ccd-afef-e3e2354fe4ae.png)

2023-01-20 03:48 UTC, VPKSoft commented
Sorry about that, I can't let the designer to be broken so the changes from the release v.5.3.2.2 are now rolled back.

2023-01-20 09:01 UTC, RobSwDev commented
Hi @VPKSoft 
Apologies - I don't use the designer, and so didn't check for that.
The reason it fails is that the path to the native libraries is not correct in the designer: the designer uses the dll in the nuget package cache rather than the build directory.
I can think of a couple of possible fixes:
1. Add better logic to locate the native dlls
2. Duplicate the native dlls in the nuget package so that they are always available in the expected relative location

I can implement 1 and resubmit a PR?

2023-01-20 20:40 UTC, VPKSoft commented
Thank you - I checked out the new PR and it works fine now 👍