port WmNcPaint from ScintillaNET 2.6 to ScintillaNET 5 for nicer rendering of 3D borders with visual styles
VPKSoft/Scintilla.NET pull request #62
Opened 2023-03-08 11:37 UTC by jmairboeck

The old ScintillaNET 2.6 version (from CodePlex) had some special handling of `WM_NCPAINT` to render the `Fixed3D` borders (which is the default) nicer and more similar to normal text boxes.

This code is a direct port of the old code (slightly modified to fit the current code style better).

2023-03-09 04:17 UTC, VPKSoft commented
Hi,
I tested this change manually and I kind of liked the previous border style, so I don't think all the other users are not going to miss the current border style after change:
![image](https://user-images.githubusercontent.com/40712699/223914677-86b78535-4ebc-4f1a-8660-1dc68fc5c695.png).

There should be some way to keep the current style in use as well - and preferably as the default one. Now the border style cannot be changed back to which it was before the change.

Could the BorderStyle be declared as new and create a custom enumeration to keep all four border style options in use?

2023-03-09 04:18 UTC, VPKSoft requested changes
The code is fine - perhaps the previous border style should be kept as default.

2023-03-12 18:48 UTC, jmairboeck commented
I added a custom BorderStyle enum with a fourth value to distinguish the two cases.

2023-03-13 03:58 UTC, VPKSoft approved these changes

2023-03-13 04:01 UTC, VPKSoft commented
Thank you 👍

2023-03-13 04:01 UTC, merged